// src/ai/flows/generate-itinerary-notes.ts
'use server';
/**
 * @fileOverview Generates itinerary notes based on a short prompt using a generative AI model.
 *
 * - generateItineraryNotes - A function that takes a prompt and returns suggested itinerary notes.
 * - GenerateItineraryNotesInput - The input type for the generateItineraryNotes function.
 * - GenerateItineraryNotesOutput - The return type for the generateItineraryNotes function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateItineraryNotesInputSchema = z.object({
  prompt: z.string().describe('A short prompt describing the itinerary.'),
});
export type GenerateItineraryNotesInput = z.infer<typeof GenerateItineraryNotesInputSchema>;

const GenerateItineraryNotesOutputSchema = z.object({
  notes: z.string().describe('Suggested itinerary notes generated by the AI model.'),
});
export type GenerateItineraryNotesOutput = z.infer<typeof GenerateItineraryNotesOutputSchema>;

export async function generateItineraryNotes(input: GenerateItineraryNotesInput): Promise<GenerateItineraryNotesOutput> {
  return generateItineraryNotesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateItineraryNotesPrompt',
  input: {schema: GenerateItineraryNotesInputSchema},
  output: {schema: GenerateItineraryNotesOutputSchema},
  prompt: `You are an itinerary assistant. Generate informative and helpful notes for the following itinerary:

Prompt: {{{prompt}}}

Notes:`,
});

const generateItineraryNotesFlow = ai.defineFlow(
  {
    name: 'generateItineraryNotesFlow',
    inputSchema: GenerateItineraryNotesInputSchema,
    outputSchema: GenerateItineraryNotesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
